### ISSUE TITLE
more BOOM! Buster issues

### ISSUE THREAD

**Issue by alex-codes-stuff** [UnderminersTeam/UndertaleModTool#1844] opened 2024-07-22 16:55 UTC
### Describe the bug

1. this. obj_player_create_0, obj_title_menu_Create_0 and also some other scripts. parsing error or smth, makes code uneditable as it wont compile
![image](https://github.com/user-attachments/assets/fcb63216-94c9-45c1-b303-9d72c6e3ece6)
2. obj_title_draw_0
![image](https://github.com/user-attachments/assets/950592b6-430e-4603-bb58-de6b5036e317)

### Reproducing steps

1. open the BOOM! Buster kickstarter demo in UTMT
2. attempt to load/edit the scripts respectively

### Setup Details

1. UTMT Bleeding Edge 
![image](https://github.com/user-attachments/assets/d9e9d891-4ea7-45d0-b921-51a0ff436be1)
2. Windows 11
3. BOOM! Buster Kickstarter Demo/2024 Demo

**Comment by colinator27** [comment] 2024-07-22 17:03
Similarly to #1842, the new decompiler fixes the decompilation process on the `underanalyzer` branch (but the compiler is not up-to-date on everything yet)

**Comment by alex-codes-stuff** [comment] 2024-07-22 17:18
alright, thanks.

**Comment by Miepee** [comment] 2024-07-25 08:11
Duplicate of #1822

**Closed by Miepee** 2024-07-25 08:11 UTC
Labels: bug
