### ISSUE TITLE
Show different flag options when modifying flags

### ISSUE THREAD

**Issue by Grossley** [UnderminersTeam/UndertaleModTool#940] opened 2022-05-26 23:36 UTC
It's hard to add new flags to modify things such as fullscreen, show cursor over game window, etc, because there is no easy way to know what valid options there are for selecting flags.

**Comment by Miepee** [comment] 2022-05-27 06:27
Duplicate of #75

**Comment by Jacky720** [comment] 2024-02-20 03:27
Closing as duplicate.

**Closed by Jacky720** 2024-02-20 03:27 UTC
