### ISSUE TITLE
deltarune chapter 1&2 (Korean version) load error

### ISSUE THREAD

**Issue by trusht12** [UnderminersTeam/UndertaleModTool#1444] opened 2023-07-29 15:09 UTC
### Describe the bug

This error occurs when opening the DeltaRune Chapter 2 Korean version.
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
           An error occured while trying to load:          
linvalid boolean value: 10944512                            
at 0598F742 while reading object                           
undertalemodlib.models.undertalefont                  
while reading item 7 of 13 in a list of                     
undertalemodlib.models.undertalefont in chunk   
font                                                                         
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

_0598F742(HEX):_
0598F650  7E FE AF FD 24 FC FE FA 67 FB 51 FD 38 FF 53 FF
0598F660  77 FD E7 FB FA FD 71 05 81 10 64 1A 3D 1E 36 1A
0598F670  A2 10 4A 06 4C FF D2 FC 30 FD F9 FD 15 FE 25 FE
0598F680  1D FF B2 00 57 01 D0 FF AD FC 05 FA 7D F9 A7 FA
0598F690  79 FB 77 FA 61 F8 7B F7 FC F8 3D FB 9F FA A9 F4
0598F6A0  90 EA D1 E0 F9 DB 29 DD 60 E1 25 E4 6E E3 74 E1
0598F6B0  BC E2 EF E9 20 F5 0B FF 63 03 34 02 74 FF 18 FF
0598F6C0  A5 01 61 04 A1 04 A9 02 1D 01 E3 01 01 04 BD 04                
0598F6D0  E9 02 BF 00 43 02 A0 09 E1 14 30 1F 66 24 F1 23
0598F6E0  A9 20 1E 1E C7 1D 82 1E 6F 1E 38 1D 59 1C 1D 1D
0598F6F0  66 1E DB 1C E1 15 9C 0A DE FF 81 FA 5A FB AC FE
0598F700  AF FF D1 FC 9A F8 9A F6 87 F7 87 F8 14 F6 68 EF
0598F710  35 E7 29 E1 EC DE 50 DF 06 E0 C5 DF 0C DF 10 DF
0598F720  5F E0 62 E2 16 E4 F6 E4 54 E5 DA E5 D4 E6 ED E7
0598F730  9C E8 F7 E8 1A EA A1 ED 69 F4 6D FD CC 05 27 0A
0598F740  91 08 **A8 37 AA 01 82 94 18 01 20 00 00 00 00 00**  //Error in this part

This bug also occurs in the Korean version of Undertale.
![error](https://github.com/krzys-h/UndertaleModTool/assets/116483314/ca215cab-d2e9-4c49-9456-5f3c686d3799)
![open](https://github.com/krzys-h/UndertaleModTool/assets/116483314/8a9c57a0-bb86-448d-835f-5dda49333764)

### Reproducing steps

1. open data.win(korean version)
2. Error Reference

### Setup Details

1. undertalemodtool version: 0.5.1.0
2. os : windows 10
3. deltarune chapter 1&2 (KOREAN VERSION)
LINK: https://team-sm.tistory.com/107

**Comment by Jacky720** [comment] 2023-07-29 15:33
Likely related to #855. Do you know how the translation was made?

**Comment by trusht12** [comment] 2023-07-30 20:38
I don't know...

**Comment by Miepee** [comment] 2024-06-01 10:31
Going to mark this as a duplicate of #855

**Closed by Miepee** 2024-06-01 10:31 UTC
Labels: bug
