### ISSUE TITLE
i cant open the data.win of undertale yellow

### ISSUE THREAD

**Issue by Poketoonix** [UnderminersTeam/UndertaleModTool#1693] opened 2024-02-24 02:11 UTC
### Describe the bug

i am getting this message.
is there some .dll i lack?"
![imagen_2024-02-23_230858243](https://github.com/UnderminersTeam/UndertaleModTool/assets/90982676/34b298dc-bc41-48f9-bcc9-b70f224518df)

### Reproducing steps

1. literally opening undertale yellow's data.win

### Setup Details

undertalemodtool v0.5.1.0

**Comment by Jacky720** [comment] 2024-02-24 02:16
Duplicate of #1554, resolved on bleeding edge. Please download a GUI build from the bleeding edge releases, it will be able to open Undertale Yellow.

**Closed by Jacky720** 2024-02-24 02:16 UTC
Labels: bug
