### ISSUE TITLE
Cannot compile code that contains Functions defined through a Struct.

### ISSUE THREAD

**Issue by nekonesse** [UnderminersTeam/UndertaleModTool#1399] opened 2023-05-27 17:19 UTC
### Describe the bug

When trying to save any code that calls a function through a struct say like "**inventory.add**", UMT refuses to compile the code and let you save.
![image](https://github.com/krzys-h/UndertaleModTool/assets/50628290/7e0704c8-28be-4922-a15d-21535efdaede)

![image](https://github.com/krzys-h/UndertaleModTool/assets/50628290/f489b9b6-1539-45ef-8446-9ef02be2428e)

### Reproducing steps

1. Open any sort of code that has accesses a function through a struct like "inventory.add". (i have my game linked in setup details, you can open up the "obj_global" draw gui event and try it there.)
2. Try to save the data.
3. The error happens.

### Setup Details

UMT Version: 0.5.1.0 Bleeding Edge (current release as of this post)
OS: Windows 10
Game: My own, MichaelTC
[MichealTC-Inventorytest.zip](https://github.com/krzys-h/UndertaleModTool/files/11582624/MichealTC-Inventorytest.zip)

**Comment by Jacky720** [comment] 2023-05-27 17:57
Duplicate of #1084, I believe.

**Comment by rgc-exists** [comment] 2023-06-17 00:50
This is just how UMT is for now.

In the Will You Snail community's case the developers are adding a function in the next update that returns an empty struct, as the next update relies heavily on structs.

We can also edit the "broken" scripts with GMML. (GMML is like UMT but you program what changes to make to the data.win, like enhanced UMLib.) GMML lets you add onto functions without having to compile them, which is good when compiling them causes an error. Unfortunately GMML does not have a UI like UMT and there is no documentation, so it's a really steep learning curve.

So if you want to use interact with structs, you might want to try to convince the devs of your game to add a function that returns an empty struct, and then use variable_struct_get() and variable_struct_set() to change the structs... And maybe using GMML.
I doubt Toby Fox will do this cause he's busy but other games might have a chance.

Ultimately... Please just add struct support to UMT XD

**Comment by Jacky720** [comment] 2024-02-20 21:14
I now have the power to act on my previous comment and close this as a duplicate (of #1084). If any further discussion is required, it can happen there.

**Closed by Jacky720** 2024-02-20 21:14 UTC
Labels: bug
