### ISSUE TITLE
Misaligned Data and Load Errors when Opening Latest ANTONBLAST Demo

### ISSUE THREAD

**Issue by DogToon64** [UnderminersTeam/UndertaleModTool#1729] opened 2024-04-17 17:32 UTC
### Describe the bug

Whenever I try to open ANTONBLAST's latest demo, Dynamite Demo 2.0, I get these error messages:
![ABDD2 0 - Error 1](https://github.com/UnderminersTeam/UndertaleModTool/assets/159098439/e97d2076-dc55-4b41-9158-742817bc53ad)
![ABDD2 0 - Error 2](https://github.com/UnderminersTeam/UndertaleModTool/assets/159098439/a99bdd4a-87ac-41f5-9f26-c4f88d4dcc87)
![ABDD2 0 - Error 3](https://github.com/UnderminersTeam/UndertaleModTool/assets/159098439/f4391453-81a3-4e7d-89bd-601289ba0c11)

### Reproducing steps

1. Open ANTONBLAST's data.win file with Undertale Mod Tool
2. Displays error messages

### Setup Details

1. [Undertale v.0.5.1.0 (Bleeding Edge build, GUI-windows-latest-Release-isBundled-true-isSingleFile-true)](https://github.com/UnderminersTeam/UndertaleModTool/releases/tag/bleeding-edge)
2. Windows 10 x64
3. [ANTONBLAST (Demo)](https://store.steampowered.com/app/1887400/ANTONBLAST/)

**Comment by TrashBandatcoot** [comment] 2024-04-17 19:54
I'll add that the Nintendo Switch version displays a different error message.

![afbeelding](https://github.com/UnderminersTeam/UndertaleModTool/assets/49070403/e79bba2c-9140-417c-9b5d-e9dc847e28b5)

**Comment by mike309game** [comment] 2024-04-17 20:46
> I'll add that the Nintendo Switch version displays a different error message.
> 
> ![afbeelding](https://private-user-images.githubusercontent.com/49070403/323360590-e79bba2c-9140-417c-9b5d-e9dc847e28b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODY5NTcsIm5iZiI6MTcxMzM4NjY1NywicGF0aCI6Ii80OTA3MDQwMy8zMjMzNjA1OTAtZTc5YmJhMmMtOTE0MC00MTdjLTliNWQtZTlkYzg0N2UyOGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDIwNDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZWM1NjRlN2VhZWNmY2NiYjY1NWNhMjQ1ZjdmNTE5ZThlODEwNzA0MGFmOWVkMmQ0Yzc0ODAxY2U3NGMxYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qnvhfCDoeK--6nMSbcnnu8HsGQkxAKuouV_KPd2TeXQ)

Seems identical to #1703, though I don't know why the switch version in specific would use LTS

**Comment by BrochachoTheBro** [comment] 2024-04-18 17:06
Having the same problem here, really need that new music...

**Comment by lucasdaweb95** [comment] 2024-04-18 23:48
> Having the same problem here, really need that new music...

If its the title screen, its up on youtube

**Comment by BrochachoTheBro** [comment] 2024-04-19 01:32
> > Having the same problem here, really need that new music...
> 
> If its the title screen, its up on youtube

moreso was referring to the new variations of cinnamon springs that are much faster than before

**Comment by lucasdaweb95** [comment] 2024-04-19 01:33
> > > Having the same problem here, really need that new music...
> > 
> > 
> > If its the title screen, its up on youtube
> 
> moreso was referring to the new variations of cinnamon springs that are much faster than before

ah, didnt know about that

**Comment by PhantomSlash64** [comment] 2024-04-19 05:55
I might be crazy but the room thing has to do with a extension called GMLive.

https://yellowafterlife.itch.io/gamemaker-live (Well wouldn't ya know, The extension causes a problem with this game)

**Comment by TrashBandatcoot** [comment] 2024-04-19 08:23
> I might be crazy but the room thing has to do with a extension called GMLive.
> 
> https://yellowafterlife.itch.io/gamemaker-live (Well wouldn't ya know, The extension causes a problem with this game)

Can't be the issues, the list of extensions hasn't changed between demo releases. Previous demo versions also used GMLive and that worked fine.

**Comment by SuperKirbylover** [comment] 2024-04-19 21:15
got the exact same error as OP, but someone else i know got this error specifically with the same version of the dynamite demo
![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/37816816/0c460cc8-d4c3-46af-bbf3-1f51c4cd8d02)

**Comment by lucasdaweb95** [comment] 2024-04-19 21:17
> got the exact same error as OP, but someone else i know got this error specifically with the same version of the dynamite demo
> 
> ![image](https://private-user-images.githubusercontent.com/37816816/324119534-0c460cc8-d4c3-46af-bbf3-1f51c4cd8d02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NjE3MTAsIm5iZiI6MTcxMzU2MTQxMCwicGF0aCI6Ii8zNzgxNjgxNi8zMjQxMTk1MzQtMGM0NjBjYzgtZDRjMy00NmFmLWJiZjMtMWY1MWM0Y2Q4ZDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDIxMTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZTgyNzMzMDM5MjZlYTZmMWI2NDkwZGFkMTdhNjgyNzA4YTkzZjk2ZmYwYzBjOGYxNTc5NDIyNTU3MjczYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AsvGk1t9AFsgvzSkYOiQNHDB2G3axtRU4S-nCZ_Wx2Q)

does not help at all 🔥

**Comment by lucasdaweb95** [comment] 2024-04-19 21:23
> > I'll add that the Nintendo Switch version displays a different error message.
> > ![afbeelding](https://private-user-images.githubusercontent.com/49070403/323360590-e79bba2c-9140-417c-9b5d-e9dc847e28b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODY5NTcsIm5iZiI6MTcxMzM4NjY1NywicGF0aCI6Ii80OTA3MDQwMy8zMjMzNjA1OTAtZTc5YmJhMmMtOTE0MC00MTdjLTliNWQtZTlkYzg0N2UyOGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDIwNDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZWM1NjRlN2VhZWNmY2NiYjY1NWNhMjQ1ZjdmNTE5ZThlODEwNzA0MGFmOWVkMmQ0Yzc0ODAxY2U3NGMxYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qnvhfCDoeK--6nMSbcnnu8HsGQkxAKuouV_KPd2TeXQ)
> 
> Seems identical to #1703, though I don't know why the switch version in specific would use LTS

might acctually be just the fact that the win file might be compiled slightly diferently from the pc version, or lts runs something that the other version doesnt and switch needs it

**Comment by Jacky720** [comment] 2024-04-19 21:25
Some basic analysis suggests the game doesn't have particle systems in rooms, which the mod tool expects in GameMaker 2023.2+. I would guess this is part of a new GameMaker version, but that needs to be verified and it leaves me wondering where any particle systems would be included.

**Comment by SuperKirbylover** [comment] 2024-04-19 22:03
> does not help at all 🔥

most unfortunate
really strange though that we both opened the same data.win and got wildly different errors though, he also has the up-to-date version of UTmodtool

**Comment by PhantomSlash64** [comment] 2024-04-24 23:23
It is working! It's opening!
https://github.com/UnderminersTeam/UndertaleModTool/pull/1737

**Comment by lucasdaweb95** [comment] 2024-05-04 10:57
> It is working! It's opening! #1737

doesnt open the switch demo tho

**Comment by Miepee** [comment] 2024-06-01 08:27
duplicate of #1703

**Closed by Miepee** 2024-06-01 08:27 UTC
Labels: bug
