### ISSUE TITLE
Invalid boolean value

### ISSUE THREAD

**Issue by NikoPalad67140** [UnderminersTeam/UndertaleModTool#1132] opened 2022-12-01 12:25 UTC
### Describe the bug

Hey guys!
I want to extract some stuff from the 1.8 update of Mega Man Maker, but whenever the objects begin getting extracted, I get the error "Invalid boolean value" for one of them.

Can someone help me?

### Reproducing steps

1. Download, extract and open Mega Man Maker.
2. Error: Invalid boolean value.

### Setup Details

UndertaleModTool version: 4.0.4
Operating system: Windows 11
GameMaker game: Mega Man Maker

**Comment by Jacky720** [comment] 2022-12-01 13:00
Try the bleeding edge versions of the tool, please.

**Comment by NikoPalad67140** [comment] 2022-12-01 13:12
And how do I use it? There's no .exe of it.

**Comment by Jacky720** [comment] 2022-12-04 04:28
Download the `GUI-windows-latest-isBundled-true-isSingleFile-true.zip ` file, and extract it to get the exe.

**Comment by Miepee** [comment] 2024-02-19 19:56
Opening Mega Man Maker (1.8.5.2) was fine for me.
However I wasn't able to extract all the code. UTMT got into a complete deadlock there. There should probably be made a seperate issue for it whenever the exact code entry (or GML code) is figured out.

**Comment by Miepee** [comment] 2024-06-01 12:28
Deadlock may have been caused by wine
Since the original issue was fixed, I'll close this issue.

**Closed by Miepee** 2024-06-01 12:28 UTC
Labels: bug, decompiler
