### ISSUE TITLE
Add alert for UTMT

### ISSUE THREAD

**Issue by fireahmedgamerYT** [UnderminersTeam/UndertaleModTool#313] opened 2020-08-21 19:59 UTC
Somemtimes while oppening a list of something you might accidantly replace something with this thing making the game easily error
So please add alert by replacing something to something with check dont show this again.

**Comment by JackoT-Bit** [comment] 2020-09-04 16:46
or at least add an undo function

**Comment by Grossley** [comment] 2021-04-19 23:30
I think this issue is in reference to #358 , which has resolved accidental swaps of items by making swapping toggleable. Furthermore, swapping can also be undone through the use of the asset order scripts. If this issue is not resolved, please feel free to reopen the issue with more information about what specifically the problem is. As for now, it's my understanding this is resolved. Closing.

**Closed as completed by Grossley** 2021-04-19 23:30 UTC
