### ISSUE TITLE
Hyper Light Drifter (stable_30fps steam build) load error 

### ISSUE THREAD

**Issue by CatoTheYounger97** [UnderminersTeam/UndertaleModTool#939] opened 2022-05-26 23:00 UTC
Hyper Light Drifter (stable_30fps steam build for windows) has this load error on opening the data.win
![unknown](https://user-images.githubusercontent.com/82458228/170592639-5d5a2e54-0147-4942-8a2d-ccbbe1c2dffb.png)

I can open it with this version of the tool:
https://github.com/krzys-h/UndertaleModTool/releases/tag/0.2.0

The "stable_30fps steam build for windows" can be accessed under the game "betas" in steam game library.

**Comment by JohnnyonFlame** [comment] 2022-05-27 00:58
This build is reportedly 1.0.0.1250, the failure is caused by `GetBuiltinSoundGroupID` in UndertaleData.cs. Fixed by setting the minimum version of the version check, the game proceeds to load and Test Run works correctly.

**Comment by Miepee** [comment] 2022-05-27 06:27
Linking for good measure:
https://github.com/krzys-h/UndertaleModTool/blob/89c7acec463440696b6bd7b1ad61cfe7eea8abe3/UndertaleModLib/UndertaleData.cs#L516

**Closed** 2024-06-02 23:21 UTC
Labels: bug, game loading warning
