### ISSUE TITLE
.win association causing severe lag when enabled with games that use data.win

### ISSUE THREAD

**Issue by Gavindg04** [UnderminersTeam/UndertaleModTool#1403] opened 2023-05-31 23:38 UTC
### Describe the bug

I was playing sonic triple trouble 16 bit fan game and it uses the data.win file and when I would download it would run at 1 fps and cant do any inputs, I had the .win association setting on the undertale mod tool and this would cause the game to lag, it shows as the blue heart icon but either I think when I open that data.win it messes up or when I downloaded it, it would just produce the same result without doing anything. From what I know it only affect that game and I dont know of any other games that have a data.win file that would produce the same result.

### Reproducing steps

1. Download or have the Undertale mod tool
2. Have .win association on
3. Download any other game that has a data.win file
4. Launch that game with or without opening the data.win file

### Setup Details

1. v0.4.0.4
2. Windows 10
3. Sonic Triple Trouble 16-bit

**Comment by Jacky720** [comment] 2024-02-20 21:20
I'm having trouble wrapping my head around how this is possible. You're saying that having UndertaleModTool installed but not running causes the game to lag? Like, if you remove the file association in regedit, the game runs fine? It's not a problem at all that has to do with actually having the tool running?

It's very strange and needs a lot of detail to try reproducing.

**Comment by Miepee** [comment] 2024-02-20 21:30
That honestly sounds more like a windows problem TBH than an UTMT one.

**Comment by Miepee** [comment] 2024-06-01 11:10
Going to close this due to being unactionable and very likely be windows related rather than UTMT related

**Closed by Miepee** 2024-06-01 11:10 UTC
Labels: bug
