### ISSUE TITLE
Memory allocation failed: Attempting to allocate 

### ISSUE THREAD

**Issue by sugushmeaky** [UnderminersTeam/UndertaleModTool#1883] opened 2024-08-23 18:12 UTC
### Describe the bug

Platform Nintendo Switch, GMS version 2023.1, UMT 6.1.0. Game does not start.

Error Code: 2-AS96A-0000

ERROR in
action number 1
of Create Event
for object <undefined>:

Memory allocation failed: Attempting to allocate 269570944 bytes

010023800D64A000 and 010080B00AD66000 attempted. Error occurs with Deltarune, Undertale crashes before start up with no error.

I'm porting another game of my own. Successfully ported via GMS 1.4. Imported file to GMS 2, runs well in Windows, no errors 

### Reproducing steps

Create game zip via GMS 2
Load data.win into UMT
Save to romfs folders (renamed game.win)
Open game, error 

### Setup Details

Platform Nintendo Switch, GMS version 2023.1, UMT 6.1.0.
010023800D64A000 and 010080B00AD66000 attempted. Error occurs with Deltarune, Undertale crashes with no error codes

This same game worked with GMS 1.4 and UMT 5.0... Ive attempted UMT 5, 6 and now 6.1. What is the most stable GMS 2 for ports?

**Comment by Miepee** [comment] 2024-08-23 18:15
> Create game zip via GMS 2
Load data.win into UMT
Save to romfs folders (renamed game.win)
Open game, error


Can you please give us more detailed reproduction steps? We need to have all resources available to reproduce, otherwise the issue is non-actionable for us.

**Comment by sugushmeaky** [comment] 2024-08-23 19:05
maybe this is more suited for the discord, I will reach out there sorry

**Comment by Miepee** [comment] 2024-08-23 20:28
Closing as this was a misunderstanding of umt being able to change the version into any arbitrary GM version than the one from the currently loaded data file

**Closed by Miepee** 2024-08-23 20:28 UTC
Labels: bug
