### ISSUE TITLE
UTMT throws a warning when you open data.win

### ISSUE THREAD

**Issue by Senjay-id** [UnderminersTeam/UndertaleModTool#1458] opened 2023-08-11 14:04 UTC
### Describe the bug

[datawin.zip](https://github.com/krzys-h/UndertaleModTool/files/12322091/datawin.zip)
I've exported a almost empty Data.win from gamemaker, then UTMT throws a warning when you open the data.win that i made.
Warning - the estimated object pool size differs from the actual size please report this on UMT Github.

### Reproducing steps

1. Open gamemaker, make a placeholder sprite.
2. Right Click the sprite then assign to texture group. choose the default
3. Hover to the tools tab and click on Texture Group
4. Change the Texture Group type to Dynamic. Also change the Texture Group Format to PNG
5. Export the game then open the data.win in UMT, throws a warning: object pool size differs from actual size

### Setup Details

1. The automatically updating UMT Bleeding Edge Commit Number : 3e9675
2. Windows 10 OS
3. n/a

**Comment by Jacky720** [comment] 2024-02-21 01:51
Tightly related to #1684-- the object pool estimation code just doesn't know what to do with external assets.

**Comment by Miepee** [comment] 2024-06-01 10:27
Gonna mark this as a duplicate of #1684

**Closed by Miepee** 2024-06-01 10:27 UTC
Labels: bug, game loading warning
