### ISSUE TITLE
deltarune chapter 1,2 unoffical korean patch load error 

### ISSUE THREAD

**Issue by newhajinyoon** [UnderminersTeam/UndertaleModTool#1476] opened 2023-09-13 14:21 UTC
### Describe the bug

This error occurs when opening the delatrune Chapter 2 Korean version.

### Reproducing steps

```
Reading misaligned at 00A79190, realiging back to 058F732
HIGH RISK OF DATA LOSS! The file is probably corrupted or procced at your own risk
```

```
An error occured while trying to load:
linvalid boolean value: 10944512
at 0598F742 while reading object
undertalemodlib.models.undertalefont
while reading item 7 of 13 in a list of
undertalemodlib.models.undertalefont in chunk
font
```

![image](https://github.com/krzys-h/UndertaleModTool/assets/61103309/10480a99-b4ee-451e-832c-d78556c400f2)

![image](https://github.com/krzys-h/UndertaleModTool/assets/61103309/95d768b1-f60b-45ba-9a3c-f67c6a72857b)

### Setup Details

1. UMT version : 0.5.1
2. Windows 11
3. undertale, but [unoffical korean patch](https://team-sm.tistory.com/107) 

the site in english :

```
After playing the game, you must select the chapter selection screen chapter and change the language to Korean on the save slot screen
Video memory (VRAM) 4GB or less does not guarantee operation and most likely does not display characters normally

delatrune Chapter 2 Korean Language Work Team

total
 casw
skill
 Imbada
translation
 Eueeeeeeeek
Inspection
 Shim Jiho, Nial, Bumbuck, Dr. Vandal

installation method

1. Select properties for the Steam library and enter the installation path
2. Overwrite extracted files
(MAC omitted)

This is a patch that needs to be downgraded to delatrune 1.0.7.
```

**Comment by Jacky720** [comment] 2023-09-13 14:27
Unless this mod was generated with UTMT, this issue can probably be folded into #855. I don't know if Altar.NET would be able to dump the strings like I would recommend for an old Undertale mod, but it's worth a shot.

**Comment by newhajinyoon** [comment] 2023-09-14 14:16
> Unless this mod was generated with UTMT, this issue can probably be folded into #855. I don't know if Altar.NET would be able to dump the strings like I would recommend for an old Undertale mod, but it's worth a shot.

is there any way to ignore the error? because I'm just trying to change the images

**Comment by Jacky720** [comment] 2024-02-21 01:57
Closing as duplicate of #1444. Regarding error ignorance, there's a PR in the works to skip broken chunks, but it wouldn't be able to rewrite the file due to critical file pointers changing and needing to be rewritten.

**Closed by Jacky720** 2024-02-21 01:57 UTC
Labels: bug
