### ISSUE TITLE
Can't open Korean translation of Undertale

### ISSUE THREAD

**Issue by spidychoi** [UnderminersTeam/UndertaleModTool#378] opened 2021-02-28 04:14 UTC
I tried to open undertale(game's) data win file but I can't open!
So I tried extracting undertale.exe and I still got error!
tell me how I can suceesfully open a file?
![error2](https://user-images.githubusercontent.com/70118125/109407746-c4f7ed00-79c6-11eb-8ae6-e275649f5b73.png)

![error](https://user-images.githubusercontent.com/70118125/109407719-616dbf80-79c6-11eb-814c-2706fdb74071.png)

**Comment by spidychoi** [comment] 2021-02-28 04:14
And do I have to root my laptop to open?

**Comment by BenjaminUrquhart** [comment] 2021-02-28 04:17
Are you trying to open Mysterytale or a PS3 game?

**Comment by Grossley** [comment] 2021-02-28 04:24
This is most likely an unofficial translation of Undertale, is this correct @spidychoi

**Comment by spidychoipro** [comment] 2021-02-28 14:10
Nop it's Korea translate version.

**Comment by spidychoipro** [comment] 2021-02-28 14:11
But not downloaded from steam

**Comment by spidychoipro** [comment] 2021-02-28 14:13
Can't load English version of deltarune chapter 1 data.win too

**Comment by spidychoipro** [comment] 2021-02-28 14:17
Or can you give tutorial about creating new file?

**Comment by spidychoipro** [comment] 2021-02-28 14:20
Nop it's Korea translate version.
But not downloaded from steam
Can't load English version of deltarune chapter 1 data.win too
Or can you give tutorial about creating new file?

**Comment by Grossley** [comment] 2021-04-19 22:51
> Yep it's Korea translate version.
> (You mean some language traslated version could not work?)
> But not downloaded from steam
> Can't load English version of deltarune chapter 1 data.win too
> Or can you give tutorial about creating new file?

Old translations cannot be loaded into UndertaleModTool through conventional means due to the cruder tools used back then (Translatale). However, workarounds are being developed right now.

**Comment by Grossley** [comment] 2021-04-20 00:44
Can you send your copy of Undertale (data.win file) to me? I can check to see if this version I am developing can be used to convert your copy of the game to the proper format.

**Comment by spidychoi** [comment] 2021-04-20 07:10
You can download korean version of undertale in below link 
[Visit Korean version of undertale](https://drive.google.com/file/d/1dTV-Kr--ppJZNyC1Y49eAEe0ANV0Ber_/view)

**Comment by Grossley** [comment] 2021-04-20 14:44
Thanks @spidychoi this will be reviewed in the coming days for how to convert this to the proper format.

**Comment by Miepee** [comment] 2024-06-02 11:59
duplicate of #855

**Closed by Miepee** 2024-06-02 11:59 UTC
