### ISSUE TITLE
Add GUI to the Linux version.

### ISSUE THREAD

**Issue by emir4169** [UnderminersTeam/UndertaleModTool#1715] opened 2024-03-23 06:16 UTC
### Which component should be improved?

UI/UX

### Describe your feature suggestion in more detail

I would like a GUI similar to the already existing one (that is only for Windows at of writing this) for the linux version.

**Comment by Jacky720** [comment] 2024-03-23 08:10
Duplicate of #460, unless there's a Linux-specific UI framework you have in mind.

**Comment by Miepee** [comment] 2024-06-01 08:36
duplicate of #460

**Closed by Miepee** 2024-06-01 08:36 UTC
Labels: enhancement
