### ISSUE TITLE
Offer different GameMaker version options when making "New" data file

### ISSUE THREAD

**Issue by Grossley** [UnderminersTeam/UndertaleModTool#1180] opened 2023-02-14 22:58 UTC
### Which component should be improved?

UI/UX

### Describe your feature suggestion in more detail

Hey when I make a new data file could it have a pop up menu with options like for GMS 1.4, 2.2, 2.3+, so on and so forth? I was trying to submit a bug report for GMS 2.3+ and I wanted to include a blank data file to test it on but the "New" option defaults to 1.4 I believe, so I could not.

**Comment by Jacky720** [comment] 2024-02-20 04:29
See also #868.

**Comment by Miepee** [comment] 2024-06-01 12:03
Going to close this as a duplicate of #868

**Closed by Miepee** 2024-06-01 12:03 UTC
Labels: enhancement, data.win format, editors
