### ISSUE TITLE
Switch statement over object_index only translates object name for the first case

### ISSUE THREAD

**Issue by MrProcastinator** [UnderminersTeam/UndertaleModTool#1452] opened 2023-08-04 00:32 UTC
### Describe the bug

Whenever a switch statement using object_index as a conditional expression is decompiled, if there's more than one case statement, only the first one will be decompiled with the object name as the case expression, whereas the rest will be generated using the integer value of each object_index.

I attach an MRE project to test this issue (rename the file to UMTSwitchObjectIndex.yyz to import it into Game Maker Studio 2).
[UMTSwitchObjectIndex.zip](https://github.com/krzys-h/UndertaleModTool/files/12255888/UMTSwitchObjectIndex.zip)

Expected output for scr_set_sprite_for_object:

```
function scr_set_sprite_for_object()
{
    switch object_index 
    {
        case obj_test1:
	        sprite_index = spr_test1
	        break
        case obj_test2:
	        sprite_index = spr_test2
	        break
        case obj_test3:
	        sprite_index = spr_test3
	        break
        case obj_test4:
	        sprite_index = spr_test4
	        break
    }

}
```

Actual output for scr_set_sprite_for_object:

```
function scr_set_sprite_for_object() //gml_Script_scr_set_sprite_for_object
{
    switch object_index
    {
        case obj_test1:
            sprite_index = spr_test1
            break
        case 1:
            sprite_index = spr_test2
            break
        case 0:
            sprite_index = spr_test3
            break
        case 3:
            sprite_index = spr_test4
            break
    }

}
```

### Reproducing steps

1. Make a switch statement with object_index as its expression
2. Write more than one case statement referencing multiple object names
3. Compile the project
4. Open the project using UndertaleModTool
5. Decompile the piece of code where the switch was written

### Setup Details

UndertaleModTool 0.5.1.0
Windows 10 Home Single Language 22H2 compilation 19045.3208
Originally found in Pizza Tower PC Steam version

**Comment by Jacky720** [comment] 2024-02-21 01:47
Duplicate of #1374.

**Closed by Jacky720** 2024-02-21 01:47 UTC
Labels: bug
