### ISSUE TITLE
Defining structs within a ds map is classified as 'unsupported syntax.'

### ISSUE THREAD

**Issue by Z3R0ON301** [UnderminersTeam/UndertaleModTool#1778] opened 2024-05-30 04:20 UTC
### Describe the bug

In GameMaker youre normally able to define structs within a ds map like:
```
ds_map_set(room_map, "rmInit", 
{
    gmin: 200,
    gmax: 700,
    bgm: 0,
    lv: 2,
    screen: 0,
}
)
```

UTMT will save a data.win file like normal unless you edit the script that has structs defined like this. If you edit the script that has this in it, even if it was a part of the vanilla game UTM will refuse to let you save and claim that this is "unsupported syntax."

This should not be unsupported syntax because it works just fine in GameMaker, and UTMT does not care about it until the script that its in gets edited in any way.

### Reproducing steps

1. Create a simple GameMaker project and define a struct within a ds map, or find a game that has structs defined within a ds map.
2. Open UTMT and edit the script this is in, anything will do.
3. Attempt to save the project.

### Setup Details

OS: Windows 11
UTMT Version: Windows Bundled Single File Bleeding Edge Release (as of 5/28/24)
Game(s): Pizza Tower, an empty gamemaker project

**Comment by CST1229** [comment] 2024-05-30 04:22
Support for structs _in UTMT_ just aren't implemented yet.

**Comment by Miepee** [comment] 2024-06-01 08:18
Duplicate of #1084

**Closed by Miepee** 2024-06-01 08:18 UTC
Labels: bug
