### ISSUE TITLE
`skeleton_animation_set_ext` causes an error when any optional argument is provided

### ISSUE THREAD

**Issue by Eric718** [UnderminersTeam/UndertaleModTool#1798] opened 2024-06-03 12:54 UTC
### Describe the bug

Noticed the error from specifically `skeleton_animation_set_ext` and `audio_play_sound`
If anything other than the required arguments are present, it throws an error, and refuses to save any changes.

Example of `skeleton_animation_set_ext`
![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/47901606/7fae6d5b-a53b-408d-9264-8fd7a5edaf7c)
![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/47901606/afa2ff7a-f3bb-44f5-9a5a-94bb703a771a)
Error thrown due to the optional loop argument being set to false, and simply omitting the argument is out of the question since the default is true.

Example of `audio_play_sound`
![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/47901606/9ee2880c-02fb-479c-bb97-086e486adffe)
![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/47901606/8298afb6-2693-4765-82ee-44ae0ce62a61)
Throws an error due to the optional volume argument, filled by `global.se_gain`

I am inclined to assume this is an issue for all other functions with optional arguments, but I have not checked.

### Reproducing steps

1. Use `skeleton_animation_set_ext` in any code.
2. Provide three arguments, those being the two required, and one optional.
3. Attempt to save changes. Prevented due to error.

### Setup Details

UndertaleModTool v0.5.1.0
Windows 11
Game is irrelevant, this is an issue that is not confined to a single game.
Also, the game itself is explicit in nature, and seeing as the issue is not something hyper-specific, I will not be linking it publicly.

**Comment by Miepee** [comment] 2024-06-03 12:55
duplicate of #1612

**Closed by Miepee** 2024-06-03 12:55 UTC
Labels: bug
