### ISSUE TITLE
The GML script when saving or click outside of the script code the \\ words \\ keep duplicating itself

### ISSUE THREAD

**Issue by Magedeline** [UnderminersTeam/UndertaleModTool#1544] opened 2023-11-17 15:06 UTC
### Describe the bug

I have an issue with the gml_obj_introimage_alarm_2 that when I click it save or click it outside of the code script it duplicated itself and  I really got annoyed about how buggy it was, if anyone can fix this before continuing's on my work of undertale mod game, and I'll be appreciated

### Reproducing steps

step 1 when you click it away or just click on the top left corner of the name files and click it save the \\ words \\ duplicated itself,
step 2 find the main problem of what causing it with the bug that duplicated itself
step 3 find a solution before fixing the problems

### Setup Details

if you look at the gml script you will see that it duplicated itself from before to after

before:

visible = true
act = 1
dongs = 0
image_speed = 0
vol = 1
pitch = 1
if (sha1_file("mus_story.ogg") == "obj_introimage_70")
    pitch = 1
caster_play(intromusic, 1, pitch)
global.typer = 11
global.faceemotion = 0
global.facechoice = 0
global.msc = 0
instance_create(0, 0, obj_introtangle)
fadercreator = 0
skip = false
global.msg[0] = scr_gettext("") //Before you play^1:take into account the original creator of the BnP mod, Blaize Mayes^1, %
global.msg[1] = scr_gettext("") //is a not very friendly person^1,  this mod doesn't support nor condone their actions^1:we are just making this mod for fun ok?^1, %
global.msg[2] = scr_gettext("obj_introimage_70") // Long ago^1, two races&ruled over Earth^1:&HUMANS and MONSTERS^6. \E1 ^1 %
global.msg[3] = scr_gettext("obj_introimage_71") // One day^1, war broke&out between the two&races^6. \E0 ^1 %
global.msg[4] = scr_gettext("obj_introimage_72") // After a long battle^1,&the humans were&victorious^6. \E1 ^1 %
global.msg[5] = scr_gettext("obj_introimage_73") // They sealed the monsters&underground with a magic&spell^6. \E0 ^1 %
global.msg[6] = scr_gettext("obj_introimage_74") // Many years later^2.^2.^5.  \E1 ^1 %
global.msg[7] = scr_gettext("obj_introimage_75") //       MT. EBOTT&         201X^9 \E0 %
global.msg[8] = scr_gettext("obj_introimage_76")// Legends say that those&who climb the mountain&never return^5.^3 \E1 %
global.msg[9] = scr_gettext("obj_introimage_78") //  \E1 %
global.msg[10] = scr_gettext("obj_introimage_79") //  ^9 ^5 \E0 %
global.msg[11] = scr_gettext("obj_introimage_80") //  ^9 ^5 ^2 \E1 %
global.msg[12] = scr_gettext("obj_introimage_81") //  ^9 ^5 ^2 \E2 %
global.msg[13] = scr_gettext("obj_introimage_82") //  ^9 ^9 ^9 ^9 ^9 ^9 \E2 %%
global.msg[14] = scr_gettext("obj_introimage_83")//  ^9 ^9 ^9 ^9 ^9 ^9 ^9  \E0 %%
global.msg[15] = scr_gettext("obj_introimage_84") //  ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 \E0 %
global.msg[16] = scr_gettext("obj_introimage_85") //  %% //  %%
mywriter = instance_create(40, 140, OBJ_WRITER)
alarm[0] = 5

after:

visible = true
act = 1
dongs = 0
image_speed = 0
vol = 1
pitch = 1
if (sha1_file("mus_story.ogg") == "obj_introimage_70")
    pitch = 1
caster_play(intromusic, 1, pitch)
global.typer = 11
global.faceemotion = 0
global.facechoice = 0
global.msc = 0
instance_create(0, 0, obj_introtangle)
fadercreator = 0
skip = false
global.msg[0] = scr_gettext("") //Before you play^1:take into account the original creator of the BnP mod, Blaize Mayes^1, %
global.msg[1] = scr_gettext("") //is a not very friendly person^1,  this mod doesn't support nor condone their actions^1:we are just making this mod for fun ok?^1, %
global.msg[2] = scr_gettext("obj_introimage_70") // Long ago^1, two races&ruled over Earth^1:&HUMANS and MONSTERS^6. \E1 ^1 %/ Long ago^1, two races&ruled over Earth^1:&HUMANS and MONSTERS^6. \E1 ^1 %
global.msg[3] = scr_gettext("obj_introimage_71") // One day^1, war broke&out between the two&races^6. \E0 ^1 %// One day^1, war broke&out between the two&races^6. \E0 ^1 %
global.msg[4] = scr_gettext("obj_introimage_72") // After a long battle^1,&the humans were&victorious^6. \E1 ^1 %// After a long battle^1,&the humans were&victorious^6. \E1 ^1 %
global.msg[5] = scr_gettext("obj_introimage_73") // They sealed the monsters&underground with a magic&spell^6. \E0 ^1 %// They sealed the monsters&underground with a magic&spell^6. \E0 ^1 %
global.msg[6] = scr_gettext("obj_introimage_74") // Many years later^2.^2.^5.  \E1 ^1 %// Many years later^2.^2.^5.  \E1 ^1 %
global.msg[7] = scr_gettext("obj_introimage_75") //       MT. EBOTT&         201X^9 \E0 %//       MT. EBOTT&         201X^9 \E0 %
global.msg[8] = scr_gettext("obj_introimage_76")// Legends say that those&who climb the mountain&never return^5.^3 \E1 %// Legends say that those&who climb the mountain&never return^5.^3 \E1 %
global.msg[9] = scr_gettext("obj_introimage_78") //  \E1 %//  \E1 %
global.msg[10] = scr_gettext("obj_introimage_79") //  ^9 ^5 \E0 %//  ^9 ^5 \E0 %
global.msg[11] = scr_gettext("obj_introimage_80") //  ^9 ^5 ^2 \E1 %//  ^9 ^5 ^2 \E1 %
global.msg[12] = scr_gettext("obj_introimage_81") //  ^9 ^5 ^2 \E2 %//  ^9 ^5 ^2 \E2 %
global.msg[13] = scr_gettext("obj_introimage_82") //  ^9 ^9 ^9 ^9 ^9 ^9 \E2 %%//  ^9 ^9 ^9 ^9 ^9 ^9 \E2 %%
global.msg[14] = scr_gettext("obj_introimage_83")//  ^9 ^9 ^9 ^9 ^9 ^9 ^9  \E0 %%//  ^9 ^9 ^9 ^9 ^9 ^9 ^9  \E0 %%
global.msg[15] = scr_gettext("obj_introimage_84") //  ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 \E0 %//  ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 ^9 \E0 %
global.msg[16] = scr_gettext("obj_introimage_85") //  %% //  %%//  %% //  %%
mywriter = instance_create(40, 140, OBJ_WRITER)
alarm[0] = 5

**Comment by Jacky720** [comment] 2023-11-17 15:11
This is a known bug with profile mode (duplicate of #1426). Also, the comments after `//` don't do anything. To edit the text there, either edit its original appearance in the "textdata_en" script, or use this format: `global.msg[0] = "Blaize Mayes sucks %"` rather than scr_gettext().

Real text will be highlighted yellow instead of green. That's a good way to check.

**Comment by Jacky720** [comment] 2023-11-17 15:38
That sounds like a separate issue that needs more detail.

**Comment by Jacky720** [comment] 2024-02-21 01:13
Duplicate of #1426.

**Closed as not planned by Jacky720** 2024-02-21 01:13 UTC
Labels: bug
