### ISSUE TITLE
Release dosent work with data.win from game ZERO Sievert

### ISSUE THREAD

**Issue by pfifo** [UnderminersTeam/UndertaleModTool#1565] opened 2023-12-10 20:26 UTC
### Describe the bug

I received a suggestion to use this tool to make mods for the game ZERO Sievert, however when I try to open the data.win file from that game I encounter a load error.
![load-error](https://github.com/krzys-h/UndertaleModTool/assets/498527/145da69d-317d-4853-a31b-fdc9f2f1ca23)
![open-error](https://github.com/krzys-h/UndertaleModTool/assets/498527/8aa5fb8a-5bec-4ecb-be24-0a6d5ef63ac9)

### Reproducing steps

to reproduce, try to open the data.win file from the game ZERO Sievert

### Setup Details

Ive tried this by running the tool both on windows 10 as well as using wine

**Comment by Miepee** [comment] 2024-01-11 14:23
Can you reproduce this with the bleeding edge release?

**Comment by pfifo** [comment] 2024-01-11 19:01
> Can you reproduce this with the bleeding edge release?

Yes (at the time the report was made)
After reviewing the code, this is not a bug, rather a feature that has not been implemented as of yet.
It seems that there is one or more new lists that have been added to TGIN.
For my application, simply disabling the error was enough to get things working.
Looking forward to proper support in future version of UMT

**Comment by Miepee** [comment] 2024-06-01 10:03
Duplicate of #1761

**Closed by Miepee** 2024-06-01 10:03 UTC
Labels: bug, game loading error
