### ISSUE TITLE
Suggestion: Formatting options for decompiled code

### ISSUE THREAD

**Issue by ithinkandicode** [UnderminersTeam/UndertaleModTool#785] opened 2022-03-12 18:49 UTC
Would it be possible to add options to change the decompiled code formatting style?

In particular:

- Make all `if()` statements use `{ ... }` (instead of 2-line ifs that don't use no curly braces)
- Add empty lines above and below `if()` and `while()` statements

I can make a personal regex script to automate the second thing, but 2-line ifs are much harder to account for.

_(edit: I originally misspoke and said "2 newlines" but meant `\n\n` ie. 1 empty line)_

**Comment by Archie-osu** [comment] 2022-03-12 18:52
I see the need for the first one (though maybe not if you just have a one-line if), but why have 2 newlines above and below ``if`` / ``while`` statements?

**Comment by ithinkandicode** [comment] 2022-03-12 21:31
> why have 2 newlines above and below `if` / `while` statements?

To space out the code a bit, so it's easier to visually parse. Like this:

| tight | spacious |
| --- | --- |
| ![tight](https://i.imgur.com/RKFcTkQ.png) | ![spacious](https://i.imgur.com/Jy6c3hl.png) |

This is a pretty simple example, with larger complex blocks it helps more.

**Comment by Miepee** [comment] 2022-06-24 14:18
Should this be merged with #944 ?

**Comment by ithinkandicode** [comment] 2022-08-29 21:01
> Should this be merged with #944 ?

Happy to merge, I'll comment on 944

**Comment by Miepee** [comment] 2024-06-02 11:49
duplicate of #944

**Closed by Miepee** 2024-06-02 11:49 UTC
