### ISSUE TITLE
Decompiler Errors in TS!Underswap Demo 2

### ISSUE THREAD

**Issue by Blueiscuteio** [UnderminersTeam/UndertaleModTool#1673] opened 2024-02-03 23:37 UTC
### Describe the bug

Many of TS!Underswap's files fail to load.

### Reproducing steps

<img width="959" alt="image" src="https://github.com/krzys-h/UndertaleModTool/assets/158784424/d556830c-9120-4db4-abe0-bc083c29c200">

### Setup Details

Used on Windows 10 with the latest version of TS!Underswap, using the latest Debug bleeding edge single-file version of UT Mod Tool.

**Comment by colinator27** [comment] 2024-06-30 22:15
Duplicate of https://github.com/UnderminersTeam/UndertaleModTool/issues/1708 - this will be fixed when the new decompiler is merged in!

**Closed by colinator27** 2024-06-30 22:15 UTC
Labels: bug, decompiler
