### ISSUE TITLE
UT repainted not opening

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [UnderminersTeam/UndertaleModTool#1402] opened 2023-05-31 21:04 UTC
### Describe the bug

stuck at reading chunk STRG because it seems that this chunk is malformed

### Reproducing steps

1. try to open this data.win for Undertale Repainted: [links expunged]

### Setup Details

UndertaleModTool bleeding edge version (gui)

**Comment by Jacky720** [comment] 2024-02-20 21:32
I've purged the links from this message as distributing full data.win files is legally risky due to piracy. I can confirm that the STRG chunk is not loading; running under debugger yields "Reading out of chunk bounds at 00B7C1B0 while reading chunk STRG". (That offset is the precise start of the next chunk, TXTR.) Likely a sub-case of #855.

**Comment by Miepee** [comment] 2024-06-01 11:13
Going to close this as a duplicate of #855

**Closed by Miepee** 2024-06-01 11:13 UTC
Labels: bug, game loading error
