### ISSUE TITLE
software doesnt like modded undertale data.win files.

### ISSUE THREAD

**Issue by adechack12** [UnderminersTeam/UndertaleModTool#586] opened 2021-09-24 20:17 UTC
![image](https://user-images.githubusercontent.com/68561498/134734692-a549cb6e-83fa-46fe-824e-a9c8cc731fd9.png)
help please?

**Comment by Grossley** [comment] 2021-09-24 20:20
Your copy of Undertale appears to be severely corrupted @adechack12

**Comment by Archie-osu** [comment] 2021-09-24 20:22
What mods were applied? Is this Undertale, or a fangame?

**Comment by adechack12** [comment] 2021-10-01 21:05
dunno if u heard me, i said modded

**Comment by Grossley** [comment] 2021-10-01 22:12
Please make sure you are loading the "data.win" file into the tool, not the game executable (do not load "UNDERTALE.exe" into UndertaleModTool). It may be called "game.ios", "game.droid", or "game.unx" on other platforms besides windows.

**Comment by adechack12** [comment] 2021-11-05 18:24
i used data.win but it still didnt let me

**Comment by Archie-osu** [comment] 2021-11-05 18:47
Then the data.win is severely corrupted. Is the error message the same when loading the data.win?

**Comment by Jacky720** [comment] 2021-11-05 18:56
And does the game run correctly normally?

**Comment by Jacky720** [comment] 2021-11-27 22:01
The tool supports *correctly*-modified data.win files, especially those produced by actual GameMaker installations or itself. However, some older tools (is the mod for translation by any chance?) corrupt the file in a way that leaves it playable but unreadable by UndertaleModTool. In order to tell if this is the case, I must ask again: Is the error message _the same?_

If it is, share the file with Grossley#2869 on Discord. If not, uh, share the file with him and the error message.

**Comment by Miepee** [comment] 2024-06-02 11:55
duplicate of #855

**Closed by Miepee** 2024-06-02 11:55 UTC
