### ISSUE TITLE
Underanalyzer Decompilation innacuracy related to clamp function

### ISSUE THREAD

**Issue by zyledev** [UnderminersTeam/UndertaleModTool#1836] opened 2024-07-18 23:02 UTC
### Describe the bug

When what I assume to be math operations ran inside of the clamp function, it skips over an argument (possibly with a similar value)

This is inside of Pizza Tower on the latest patch a the time of this issue.
decompilation output:
`x = clamp(x, other.current_room.x + other.current_room.width);`
what it should be:
`x = clamp(x, other.current_room.x, other.current_room.x + other.current_room.width);`

### Reproducing steps

1. Open UndertaleModTool compiled from the Underanalyzer branch
2. Open the data.win of Pizza Tower
3. go to script: "instance_edit_update"
4. line 93

### Setup Details

UndertaleModTool-Underanalyzer commit: 6395ad7,
Windows 11 64 bit ,
Pizza Tower
https://store.steampowered.com/app/2231450/Pizza_Tower/

**Comment by zyledev** [comment] 2024-07-18 23:10
Would also like to mention that this is my underanalyzer version: [14b2e30](https://github.com/UnderminersTeam/Underanalyzer/commit/14b2e308175cfd1afde417e8ee091c80a98136e1)

**Comment by zyledev** [comment] 2024-07-18 23:16
[issue_project.zip](https://github.com/user-attachments/files/16289988/issue_project.zip)
Here's a little project showcasing the issue, make sure to compile it using LTS!
![ccGFU8VcEo](https://github.com/user-attachments/assets/8c686db5-96ea-4588-8523-8d23409e447c)

**Comment by colinator27** [comment] 2024-07-18 23:49
I cannot reproduce this - the output looks fine for me.

**Comment by zyledev** [comment] 2024-07-18 23:54
[data.zip](https://github.com/user-attachments/files/16290148/data.zip)
Here's a build that has the issue for me.
![image](https://github.com/user-attachments/assets/bbb501ca-7103-49a4-9617-777ddd88e5fb)

**Comment by colinator27** [comment] 2024-07-18 23:55
Output still looks correct. It's supposed to be what the screenshot shows, right?

**Comment by zyledev** [comment] 2024-07-19 00:00
that's really strange, here's my current build which is having the issue.
[net6.0-windows.zip](https://github.com/user-attachments/files/16290172/net6.0-windows.zip)

**Comment by Jacky720** [comment] 2024-07-19 00:12
I still can't reproduce. Is the screenshot the correct or the incorrect result?

**Comment by colinator27** [comment] 2024-07-19 02:30
This was determined to be some strange compilation issue, and was not reproducible with GitHub Actions builds. I'll close this for now, but this can be reopened if the issue crops up again in the future for some reason.

**Closed by colinator27** 2024-07-19 02:30 UTC
Labels: bug
